---
networks:
  base-django-network:
    driver: bridge

volumes:
  dev-db-data:


services:
  # ---------------------------------------------------------------------
  # | Django Api Service                                                |
  # ---------------------------------------------------------------------
  django-api-service:
    build:
      context: ../../../ 
      dockerfile: .${API_PROJECT_PATH}/Dockerfile.dev
      args:
        - DEV=true
        - API_PROJECT_PATH=${API_PROJECT_PATH}
    ports:
      - "8000:8000"
    depends_on:
      - postgresql-database
    env_file:
      - ../../configuration/env/.${PROJECT_NAME}.compose.env
    volumes:
      - ../../../${API_PROJECT_PATH}/app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - base-django-network

  # ---------------------------------------------------------------------
  # | Postgres Database                                                 |
  # ---------------------------------------------------------------------
  postgresql-database:
    image: postgres:13-alpine
    env_file:
      - ../../configuration/env/.${PROJECT_NAME}.compose.env
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    networks:
      - base-django-network



